In [ ]:
import pandas as pd

df = pd.read_csv(".././sample_data/sample.csv")
df.head()

      name  age     pref
0   Tanaka   25    Tokyo
1   Suzuki   30  Saitama
2     Sato   20    Aichi
3  Nishino   49     Saga
4   Oosawa   58   Kouchi

In [8]:
import pandas as pd

df = pd.read_csv(".././sample_data/sample.csv")
df.iloc[::2, ::2]

       name     pref
0    Tanaka    Tokyo
2      Sato    Aichi
4    Oosawa   Kouchi
6  Katagiri  Fukuoka
8  Fujisawa  Ibaraki

In [ ]:
import pandas as pd

df = pd.read_csv(".././sample_data/sample.csv")
df.query("age >= 35 and pref == 'Tokyo'")

TypeError: 'method' object is not subscriptable